{
  lib,
  pkgs,
  ...
}:
let
  # Extensions/themes installed from AMO through enterprise policies.
  # key = extension id, value = AMO slug.
  extensions = {
    "addon@darkreader.org" = "darkreader";
    "saladict@crimx.com" = "ext-saladict";
    "{29f42579-9618-4dc7-8647-eaad7cd3343e}" = "trancyfordesktop";
    "extension@one-tab.com" = "onetab";
    "{c2c003ee-bd69-42a2-b0e9-6f34222cb046}" = "auto-tab-discard";
    # Tokyo Night theme (switch the slug to `tokyo-night-storm` to match the
    # `tokyonight-storm` colorscheme used in Neovim).
    "{4520dc08-80f4-4b2e-982a-c17af42e5e4d}" = "tokyo-night-milav";
  };

  # The theme to activate by default (must match an entry above).
  activeTheme = "{4520dc08-80f4-4b2e-982a-c17af42e5e4d}";

  # Prefs Firefox reads very early during startup. Setting them as
  # `defaultPref` through `librewolf.overrides.cfg` is too late, so use the
  # Preferences policy to write real user prefs. Only `browser.`, `intl.`,
  # `layout.`, `sidebar.`, `ui.` and similar prefixes are allowed here
  # (privacy/identity prefs are not).
  earlyPrefs = {
    "ui.systemUsesDarkTheme" = 1;
    "browser.theme.toolbar-theme" = 0;
    "browser.theme.content-theme" = 0;
    "layout.css.prefers-color-scheme.content-override" = 0;
    "sidebar.revamp" = true;
    "sidebar.visibility" = "always-show";
    "sidebar.position_start" = true;
    "sidebar.main.tools" = "history,bookmarks,syncedtabs";
    "sidebar.verticalTabs" = true;
    "intl.accept_languages" = "zh-CN,zh,en-US,en";
    "webgl.disabled" = false;
    # Activate the Tokyo Night theme once it is installed by the policy above.
    "extensions.activeThemeID" = activeTheme;
  };
  # Overrides file content (same format as the Home Manager module
  # generates: `defaultPref(...)`). Written to both the legacy and the XDG
  # location below.
  mkOverrides =
    prefs:
    "// Generated by Home Manager.\n\n"
    + lib.concatStrings (
      lib.mapAttrsToList (name: value: ''defaultPref("${name}", ${builtins.toJSON value});
'') prefs
    );

  # Prefs the Preferences policy is not allowed to touch, so they go through
  # `librewolf.overrides.cfg` (defaultPref, loaded after LibreWolf's own
  # mozilla.cfg, so these win).
  settings = {
    # --- keep cookies / history across restarts -------------------
    "privacy.sanitize.sanitizeOnShutdown" = false;
    # Firefox 128+ moved the "Clear on shutdown" options to _v2 prefs;
    # LibreWolf sets `privacy.sanitize.clearOnShutdown.hasMigratedToNewPrefs3`,
    # which makes the old `privacy.clearOnShutdown.*` prefs ineffective.
    "privacy.clearOnShutdown_v2.cookiesAndStorage" = false;
    "privacy.clearOnShutdown_v2.browsingHistoryAndDownloads" = false;
    "privacy.clearOnShutdown_v2.historyFormDataAndDownloads" = false;
    "privacy.clearOnShutdown_v2.formdata" = false;
    "privacy.clearOnShutdown_v2.siteSettings" = false;
    # Legacy prefs, kept for older LibreWolf/Firefox builds.
    "privacy.clearOnShutdown.cookies" = false;
    "privacy.clearOnShutdown.history" = false;
    "privacy.clearOnShutdown.sessions" = false;
    "privacy.clearOnShutdown.offlineApps" = false;
    "network.cookie.lifetimePolicy" = 0;

    # --- dark mode (RFP is what pins the content scheme to light) --
    "privacy.resistFingerprinting" = false;
    "privacy.resistFingerprinting.pbmode" = false;

    # --- Firefox Account / Sync -----------------------------------
    # LibreWolf disables FxA by default; this pref controls the whole
    # feature (including the sign-in UI).
    "identity.fxaccounts.enabled" = true;
  };
in
{
  # LibreWolf stores its profile under the XDG config dir
  # (`~/.config/librewolf/librewolf/`) and loads `librewolf.overrides.cfg`
  # from there, but the Home Manager module only writes it to `~/.librewolf/`.
  # Write the same content to the XDG location too.
  home.file.".config/librewolf/librewolf/librewolf.overrides.cfg".text = mkOverrides settings;

  # LibreWolf fixes and additions.
  programs.librewolf = {
    enable = true;

    # Use the official (multi-locale) LibreWolf build. The nixpkgs source
    # build only ships en-US, and installing the zh-CN language pack through
    # policies makes Firefox remove it on every other start (the UI then
    # alternates between Chinese and English). The official build has all
    # locales bundled, so no language pack is needed.
    package = pkgs.librewolf-bin;

    policies = {
      # Set the UI language through LocaleService (a plain `defaultPref` is
      # ignored/cleared by the locale negotiation).
      RequestedLocales = [ "zh-CN" ];

      Preferences = lib.mapAttrs (_name: value: {
        Value = value;
        Status = "user";
      }) earlyPrefs;

      # Extensions installed from AMO. `normal_installed` keeps them updated
      # and present but lets you disable/remove them in about:addons.
      ExtensionSettings = lib.mapAttrs (_id: slug: {
        installation_mode = "normal_installed";
        install_url = "https://addons.mozilla.org/firefox/downloads/latest/${slug}/latest.xpi";
        private_browsing = true;
      }) extensions;
    };

    # Prefs that the Preferences policy is not allowed to touch are still set
    # through `librewolf.overrides.cfg` (defaultPref).
    inherit settings;
  };
}
