active-opacity = 1.000000;
backend = "glx";
blur-background = true;
blur-method = "dual_kawase";
blur-strength = 3;
blur-background-exclude = [
  "class_g = 'slop'",
  "class_g = 'maim'",
];
corner-radius = 0;
fade-delta = 10;
fade-exclude = [ "window_type *= 'menu'" , "name ~= 'Firefox$'" , "focused = 1" ];
fade-in-step = 0.050000;
fade-out-step = 0.050000;
fading = true;
frame-opacity = 1;
inactive-opacity = 0.980000;
opacity-rule = [  ];
shadow = false;
shadow-exclude = [  ];
shadow-offset-x = -15;
shadow-offset-y = -15;
shadow-opacity = 0.750000;
use-damage = false;
vsync = true;
wintypes: { dropdown_menu = { opacity = 1.000000; }; popup_menu = { opacity = 1.000000; }; };
