#!/bin/sh

# battery block
capacity=$(cat /sys/class/power_supply/BAT0/capacity 2>/dev/null)
status=$(cat /sys/class/power_supply/BAT0/status 2>/dev/null)

case $status in
    "Charging") icon="󰂏 ";;
    "Discharging") icon="󰂌 ";;
    "Full") icon="󰁹 ";;
    *) icon="";;
esac

if [ "$capacity" -ge 89 ]; then
	icon="󰚥 "
fi

printf "%s %s%%\n" "$icon" "$capacity"

