#!/bin/sh

#sink=$(wpctl inspect @DEFAULT_AUDIO_SINK@ 2>/dev/null)
sink=$(wpctl get-volume @DEFAULT_AUDIO_SINK@ 2>/dev/null)

vol=$(echo "$sink" | grep -m 1 "Volume:" | awk '{print $2*100}')

if echo "$sink" | grep -q "\[MUTED\]"; then
	muted=true
else
	muted=false
fi

if [ "$muted" = true ]; then
	icon="[MUTE]"
elif [ "$vol" -ge 70 ]; then
    icon="󰕾"
elif [ "$vol" -ge 30 ]; then
    icon=""
else
    icon="󰖀"
fi

printf "%s %s%%\n" "$icon" "$vol"
